"""
Agent C — Writer / Summarizer
Specialization: text summarization, report writing
Port: 8003
"""
import json, uuid, hashlib
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI(title="AgentC - Writer", version="1.0.0")

CAPABILITIES = ["summarization", "report-writing", "text-analysis"]
PRICE_ETH    = 0.0005

# ── Models ────────────────────────────────────────────────────────
class TaskRequest(BaseModel):
    taskId:    str = ""
    taskType:  str
    input:     dict
    budgetEth: float = 0.0005

class TaskResponse(BaseModel):
    taskId: str
    status: str
    output: dict
    proof:  str

# ── Health ────────────────────────────────────────────────────────
@app.get("/")
def info():
    return {
        "agent":        "AgentC-Writer",
        "capabilities": CAPABILITIES,
        "priceEth":     PRICE_ETH,
        "status":       "ready"
    }

# ── Core task handler ─────────────────────────────────────────────
@app.post("/agent/task", response_model=TaskResponse)
async def handle_task(req: TaskRequest):
    task_id = req.taskId or str(uuid.uuid4())

    if req.taskType == "summarization":
        raw_results = req.input.get("results", [])
        topic       = req.input.get("topic", "the topic")
        summary     = _summarize(topic, raw_results)
        output      = {"topic": topic, "summary": summary, "wordCount": len(summary.split())}

    elif req.taskType == "report-writing":
        topic    = req.input.get("topic", "")
        sections = req.input.get("sections", [])
        report   = _write_report(topic, sections)
        output   = {"topic": topic, "report": report}

    else:
        raise HTTPException(400, f"Unsupported taskType: {req.taskType}")

    proof = "0x" + hashlib.sha256(json.dumps(output).encode()).hexdigest()
    return TaskResponse(taskId=task_id, status="completed", output=output, proof=proof)


# ── Writing helpers ───────────────────────────────────────────────
def _summarize(topic: str, results: list) -> str:
    if not results:
        return f"No data was provided for summarization of '{topic}'."

    snippets = " ".join(r.get("snippet", "") for r in results if isinstance(r, dict))

    # In production: call OpenAI / Anthropic here
    # For demo: structured template summary
    summary = (
        f"**Summary: {topic}**\n\n"
        f"Based on {len(results)} sources gathered by the Data Fetcher agent, "
        f"here is a concise overview:\n\n"
        f"{snippets[:500]}...\n\n"
        f"**Key Takeaways:**\n"
        f"- The topic '{topic}' has significant recent developments as of 2026.\n"
        f"- Multiple authoritative sources confirm ongoing activity in this space.\n"
        f"- Further research is recommended for deeper domain-specific insights.\n\n"
        f"*This summary was autonomously generated by AgentC-Writer "
        f"as part of the AgentHire Protocol.*"
    )
    return summary

def _write_report(topic: str, sections: list) -> str:
    lines = [f"# Report: {topic}\n"]
    for s in sections:
        lines.append(f"## {s.get('title','Section')}\n{s.get('content','')}\n")
    return "\n".join(lines)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8003)
